apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-poc
  labels:
    app: events-poc
spec:
  selector:
    matchLabels:
      app: events-poc
  replicas: 2
  template:
    metadata:
      labels:
        app: events-poc
    spec:
      containers:
        - name: events-poc
          image: simonwfarrow/events-poc:c4894a9ae4f3bb7e583a6ce53eb11c241c225eee
      imagePullSecrets:
        - name: regcred
